export let data=[
    {
        name: "article1",
        autor: "Kondzio",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Gold_nugget_%28Australia%29_4_%2816848647509%29.jpg/1200px-Gold_nugget_%28Australia%29_4_%2816848647509%29.jpg",
        text: "The precious metals industry differs considerably from those for most other metals and minerals in being driven mainly by the high prices and special properties of these metals. Precious metals (comprising gold, silver, platinum, palladium, rhodium, and iridium) occur rarely in nature and typically in only trace concentrations, requiring complex and costly mining and refining processes. Precious metals have unique and highly valued properties, such as corrosion resistance, high conductivity, and catalytic capabilities, and are increasingly used in high-technology applications and devices. Gold and silver,and, more recently, platinum and palladium are sought after for investment purposes. The precious metals industry is complex, and today is confronted by many challenges. This chapter discusses issues of increased demand coupled with decreasing grades, increasing prices, increasing production costs, and deleterious byproducts; geopolitics, public perception, and regulations surrounding the primary industry; labor unrest; artisanal and illegal mining; sustainability and water and energy usage. Various mitigating approaches are addressed, including an increased focus on recycling, the concepts of thrifting and substitution, and the emergence of new technologies. In conclusion, a positive prognosis for the future of this industry is offered.",
    },
    {
        name: "article2",
        autor: "SuperKondzio420",
        image: "https://d212xeqkdfelnt.cloudfront.net/blog_oneroyal/wp-content/uploads/2018/02/22144237/King-World-News-James-Turk-This-Is-The-Real-Reason-The-Government-Created-Fridays-Flash-Crash-In-Silver-864x400_c-2.jpg",
        text: "The precious metals industry differs considerably from those for most other metals and minerals in being driven mainly by the high prices and special properties of these metals. Precious metals (comprising gold, silver, platinum, palladium, rhodium, and iridium) occur rarely in nature and typically in only trace concentrations, requiring complex and costly mining and refining processes. Precious metals have unique and highly valued properties, such as corrosion resistance, high conductivity, and catalytic capabilities, and are increasingly used in high-technology applications and devices. Gold and silver,and, more recently, platinum and palladium are sought after for investment purposes. The precious metals industry is complex, and today is confronted by many challenges. This chapter discusses issues of increased demand coupled with decreasing grades, increasing prices, increasing production costs, and deleterious byproducts; geopolitics, public perception, and regulations surrounding the primary industry; labor unrest; artisanal and illegal mining; sustainability and water and energy usage. Various mitigating approaches are addressed, including an increased focus on recycling, the concepts of thrifting and substitution, and the emergence of new technologies. In conclusion, a positive prognosis for the future of this industry is offered.",
    },
]
